### ISSUE TITLE
plugincollection-plugin-name-conflict

### ISSUE THREAD

**Issue by joachimdoerr** [Mistralys/ckeditor5-paste-plaintext#3]
Since ckeditor5 version 23.1.0 I got the follow issue: 
CKEditorError: plugincollection-plugin-name-conflict {"pluginName":"PastePlainText"}

<img width="1668" alt="Bildschirmfoto 2020-11-23 um 12 04 55" src="https://user-images.githubusercontent.com/1191549/99955143-1ec39800-2d84-11eb-8160-5ba70ca7a874.png">

**Comment by Mistralys** [comment]
Hi Joachim,

That almost sounds like there is another plugin with the same name. I have not updated my application to the new version yet, so I haven't tested the plugin with ckeditor v23.1.0.

I will try to have a look in the coming days, but without any promises - I have a deadline I need to keep, so I may only get to it afterwards.

Regards,

Sebastian.

**Comment by joachimdoerr** [comment]
Hello @Mistralys, 

I check that again and notice that the clipboard plugin contains PastPlainText too. I change the plugin to PlainTextPast and it works fine. So I think you have to rename the plugin byself. If the name change to PlainTextPast for you good, I will create a pull request, it is not a big deal. 

Best Regards Joachim

**Comment by Mistralys** [comment]
Hi @joachimdoerr,

Ah yes, I see that they have a plugin bundled with the same name. Bummer :|

If you're up to creating a pull request, that would be great! I think if we rename the plugin to `PasteAsPlainText`, that would solve the problem nicely. 

Cheers,

Sebastian.

**Comment by joachimdoerr** [comment]
https://github.com/Mistralys/ckeditor5-paste-plaintext/pull/4

**Comment by Mistralys** [comment]
Thanks a bundle Joachin, the pull request has been merged.
