### ISSUE TITLE
Cannot read property 'toView' of undefined

### ISSUE THREAD

**Issue by eddherrera** [Mistralys/ckeditor5-paste-plaintext#5]
Plugin not pasting content when toggle is On.

plaintext.js  => line41

ckeditor version: 27.0.0

**Comment by Mistralys** [comment]
Hi @eddherrera,

Thanks for the info - I checked, in CKEditor 27 they changed the way to access the clipboard. I updated the `plaintext.js` file, please check if it works with the current master.

**Comment by eddherrera** [comment]
it works.
Thanks for the quick response.
